// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjQ3iMCKHUkDosPE_ZUo1SSyw_oeuqVA',
    appId: '1:1012017544670:web:0054a23b3e7dcc40d3b14f',
    messagingSenderId: '1012017544670',
    projectId: 'flutter-813c3',
    authDomain: 'flutter-813c3.firebaseapp.com',
    storageBucket: 'flutter-813c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbIKp_cWXMHLQ98WJr1zYd--qSxTtU4vU',
    appId: '1:1012017544670:android:ca81f492c3820023d3b14f',
    messagingSenderId: '1012017544670',
    projectId: 'flutter-813c3',
    storageBucket: 'flutter-813c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJJ6fE56Go5yA6qR8u_ra9plMevO5wqg',
    appId: '1:1012017544670:ios:39a46c31e939b9ccd3b14f',
    messagingSenderId: '1012017544670',
    projectId: 'flutter-813c3',
    storageBucket: 'flutter-813c3.appspot.com',
    iosClientId:
        '1012017544670-lq6jti2cvl578998a8ka32nibq7i979e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJJ6fE56Go5yA6qR8u_ra9plMevO5wqg',
    appId: '1:1012017544670:ios:39a46c31e939b9ccd3b14f',
    messagingSenderId: '1012017544670',
    projectId: 'flutter-813c3',
    storageBucket: 'flutter-813c3.appspot.com',
    iosClientId:
        '1012017544670-lq6jti2cvl578998a8ka32nibq7i979e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
